       
<div class="discussion">
	<div class="posts">
		<?php	foreach($resultPostsRequest as $resultPostRequest):?>
				<p class="postList" >
					<?=$resultPostRequest["title_post"]?>
					<br/>
					Créé par :<b><?=$resultPostRequest["pseudo"]?></b>
					<br/>
					<small>le: <?=$resultPostRequest["date_post"]?></small>
				</p>
				<form method="get" action="discussion" class="form-comments display">
					<ul>
						<li>
							<input type="hidden" name="idPost" value="<?= $resultPostRequest['id'] ?>">
						</li>
						<li>
							<label for="answer"></label>
							<textarea name="answer" id="answer" rows="10" placeholder="Ta réponse" required></textarea>
						</li>
						<li>
							<button class="submitAnswer">Kick</button>
						</li>
					</ul>
				</form>
		<?php endforeach; ?>
  </div>
		
	<form method="post">
		<ul class="ulDiscussion">
			<li>
				<label for="posts"></label>
				<input type="text" id="posts" name="posts" placeholder="Ton sujet" required/>
			</li>
			<li>
				<label for="article"></label>
				<textarea name="article" id="article" rows="10" placeholder="Explique nous tout" required></textarea>
			</li>
			<li>
				<input type="submit" class="button" value="Kick" name="sub" />
				<button type="reset" class="button">Effacer</button>
			</li>
		</ul>
	</form>
</div>