       
<div class="discussion">

	<?php foreach($resultPostsRequest as $resultPostRequest):?>
		<a href="#">
			<p class="postList" >
				<?=$resultPostRequest["title_post"]?>
				<br/>
				Créé par :<b><?=$resultPostRequest["pseudo"]?></b>
				<br/>
				<small>le: <?=$resultPostRequest["date_post"]?></small>
			</p>
			<form method="post" action="discussion" data-idPost="<?= $resultPostRequest["id"]?>">
				<ul>
					<li>
						<label for="answer"></label>
						<textarea name="answer" id="answer" rows="10" placeholder="Ta réponse" required></textarea>
					</li>
					<li>
						<button class="submitAnswer">Kick</button>
					</li>
				</ul>
			</form>
		</a>
	<?php endforeach; ?>
		
	<form method="post">
		<ul class="ulDiscussion">
			<li>
				<label for="posts"></label>
				<input type="text" id="posts" name="posts" placeholder="Ton sujet" required/>
			</li>
			<li>
				<label for="article"></label>
				<textarea name="article" id="article" rows="10" placeholder="Explique nous tout" required></textarea>
			</li>
			<li>
				<input type="submit" class="button" value="Kick" name="sub" />
				<button type="reset" class="button">Effacer</button>
			</li>
		</ul>
	</form>
</div>