
<div class="discussion">
	<div class="posts">
		<?php	foreach($resultPostsRequest as $resultPostRequest):?>
			<div class="postElement">
        <p class="postList">
  				<?=$resultPostRequest["title_post"]?>
  				<br />
  				Créé par :<b><?=$resultPostRequest["pseudo"]?></b>
  				<br />
  				<small>le: <?=$resultPostRequest["date_post"]?></small>
        </p>
        <?php foreach($resultCommentsRequest as $resultCommentRequest):?>
          <p class="text-comments display">
          <?php if ($resultCommentRequest["id_post"] == $resultPostRequest['id']):?>
              <?= $resultCommentRequest["comment"] ?>
          <?php endif; ?>
          </p>
        <?php endforeach; ?>
				<form method="get" action="discussion.php" class="form-comments display">
					<ul>
						<li>
							<input type="hidden" name="idPost" value="<?= $resultPostRequest['id'] ?>">
						</li>
						<li>
							<label for="comment"></label>
							<textarea name="comment" id="comment" rows="10" placeholder="Ta réponse" required="required"></textarea>
						</li>
						<li>
							<button class="submitAnswer">Kick</button>
						</li>
					</ul>
				</form>
      </div>
		<?php endforeach; ?>
  </div>

	<form method="post">
		<ul class="ulDiscussion">
			<li>
				<label for="posts"></label>
				<input type="text" id="posts" name="posts" placeholder="Ton sujet" required/>
			</li>
			<li>
				<label for="article"></label>
				<textarea name="article" id="article" rows="10" placeholder="Explique nous tout" required></textarea>
			</li>
			<li>
				<input type="submit" class="button" value="Kick" name="sub" />
				<button type="reset" class="button">Effacer</button>
			</li>
		</ul>
	</form>
</div>
