<!doctype html>
<html class="no-js" lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>The tricking</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!--google font -->
        <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet"> 

        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
        <link rel="stylesheet" href="css/normalize.min.css">
        <link rel="stylesheet" href="css/main.css">

        <script src="https://code.jquery.com/jquery-3.2.1.min.js"
              integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
              crossorigin="anonymous"></script>
        <script src="js/main.js"></script>

        <!--[if lt IE 9]>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script>window.html5 || document.write('<script src="js/vendor/html5shiv.js"><\/script>')</script>
        <![endif]-->
    </head>
    <body> 
        <header>
            <h1><a href="./">The Tricking</a></h1>
                 
            <nav class="layout">
                <ul>
                    <li>
                        <a class="left" id="tutaux" href="tutaux.php">Tutaux</a>                
                    </li>             
                    <li>
                        <a class="left" href="#">Events</a>
                    </li>           
                    <!--<li>
                        <a class="right" href="#">Plan</a>
                    </li>-->
                    <li>
                        <a class="right" href="discussion.php">Discussion</a>
                    </li>
                </ul>
            </nav>
            <!-- Ligne de séparation -->
            <div style="background-color: #446B8A; height: 3px;"></div>
        </header>        
        <main>

        <?php include $page.".phtml" ?>
            
        </main>
        <footer>
            <div id="footerLine"></div>
        </footer>
    </body>
</html>
