<form method="post">
	<ul>
		<li>
			<label>Nom</label>
			<input type="text" name="lastName" required>
		</li>
		<li>
			<label>Prénom</label>
			<input type="text" name="firstName" required>
		</li>
		<li>
			<label>Pseudo</label>
			<input type="text" name="pseudo" required>
		</li>
		<li>
			<label>Mot de passe</label>
			<input type="text" name="password" required>
		</li>
		<li>
			<input type="submit" name="subLogin" value="Inscription">
		</li>
	</ul>
</form>
