
<div class="tutaux">
	<h1>Les tutaux</h1>
	<ul>
		<li>
			<h3 class="elans" ><a href="#elans">Elans</a></h3>
			<ul>
				<li>
					<h4 class="elan display">Roue</h4>
					<video src="video/coeur.mp4" controls="controls" poster="img/coeur.jpg" class="elan display"></video>
				</li><!--
				--><li>
					<h4 class="elan display">Roue une main</h4>	
					<video src="video/coeur.mp4" height="270" width="444" controls="controls" poster="img/coeur.jpg" class="elan display"></video>	
				</li><!--
				--><li>
					<h4 class="elan display">Roue sans les main</h4>
					<video src="video/coeur.mp4" height="270" width="444" controls="controls" poster="img/coeur.jpg" class="elan display"></video>
				</li>
			</ul>
		</li>
		
		<li>			
			<h3 class="kicks" ><a href="#kicks">Kick</a></h3>
			<ul>
				<li>
					<h4 class="kick display">Hook</h4>		
				</li><!--
				--><li>
					<h4 class="kick display">720</h4>
				</li><!--	
				--><li>	
					<h4 class="kick display">540</h4>
				
			</ul>
		</li>

		<li>
			<h3 class="acros" ><a href="#acros">Acrobaties</a></h3>
			<ul>
				<li>
					<h4 class="acro display">Salto Arrière</h4>
				</li><!--
				--><li>
					<h4 class="acro display">Salto Avant</h4>
				</li><!--
				--><li>	
					<h4 class="acro display">Salto Vrillé</h4>
				</li>
			</ul>
		</li>
	</ul>
		
</div>