
<div class="tutaux">
	<h1>Les tutaux</h1>
	<div id="player"></div>
	<ul>
		<li>
			<h3 class="elans" ><a href="#elans">Elans</a></h3>
			<ul>
				<li>
					<iframe id="player" type="text/html" class="elan display"
				  	src="http://www.youtube.com/embed/cQ0P6d8c-KE?enablejsapi=1&origin=http://example.com"
				  	frameborder="0"></iframe>
					<legend class="elan display roue">Roue</legend>
				</li><!--
				--><li>
					<iframe id="player" type="text/html" class="elan display"
				  	src="http://www.youtube.com/embed/cQ0P6d8c-KE?enablejsapi=1&origin=http://example.com"
				  	frameborder="0"></iframe>
					<legend class="elan display">Roue une main</legend>
				</li><!--
				--><li>
					<iframe id="player" type="text/html" class="elan display"
				  	src="http://www.youtube.com/embed/cQ0P6d8c-KE?enablejsapi=1&origin=http://example.com"
				  	frameborder="0"></iframe>
					<legend class="elan display">Roue sans les main</legend>
				</li>
			</ul>
		</li>

		<li>
			<h3 class="kicks" ><a href="#kicks">Kick</a></h3>
			<ul>
				<li>
					<iframe id="player" type="text/html" class="kick display"
				  	src="http://www.youtube.com/embed/cQ0P6d8c-KE?enablejsapi=1&origin=http://example.com"
				  	frameborder="0"></iframe>
					<legend class="kick display">Hook</legend>
				</li><!--
				--><li>
					<iframe id="player" type="text/html" class="kick display"
				  	src="http://www.youtube.com/embed/cQ0P6d8c-KE?enablejsapi=1&origin=http://example.com"
				  	frameborder="0"></iframe>
					<legend class="kick display">720</legend>
				</li><!--
				--><li>
					<iframe id="player" type="text/html" class="kick display"
				  	src="http://www.youtube.com/embed/cQ0P6d8c-KE?enablejsapi=1&origin=http://example.com"
				  	frameborder="0"></iframe>
					<legend class="kick display">540</legend>
				</li>
			</ul>
		</li>

		<li>
			<h3 class="acros" ><a href="#acros">Acrobaties</a></h3>
			<ul>
				<li>
					<legend class="acro display">Salto Arrière</legend>
				</li><!--
				--><li>
					<legend class="acro display">Salto Avant</legend>
				</li><!--
				--><li>
					<legend class="acro display">Salto Vrillé</legend>
				</li>
			</ul>
		</li>
	</ul>

</div>
