<h1>Les tutaux</h1>
<div class="tutaux">

	<h3 class="elans" id="elans"><a href="#elans">Elans</a></h3>
	<hr/>
	<h4 class="elan display">Roue</h4>
	<video src="video/coeur.mp4" controls="controls" poster="img/coeur.jpg" class="elan display"></video>
	<h4 class="elan display">Roue une main</h4>	
	<video src="video/coeur.mp4" height="270" width="444" controls="controls" poster="img/coeur.jpg" class="elan display"></video>	
	<h4 class="elan display">Roue sans les main</h4>
	<video src="video/coeur.mp4" height="270" width="444" controls="controls" poster="img/coeur.jpg" class="elan display"></video>

	<h3 class="kicks" id="kicks"><a href="#kicks">Kick</a></h3>
	<hr/>
	<h4 class="kick display">Hook</h4>		
	<h4 class="kick display">720</h4>		
	<h4 class="kick display">540</h4>
	
	<h3 class="acros" id="acros"><a href="#acros">Acrobaties</a></h3>
	<hr/>
	<h4 class="acro display">Salto Arrière</h4>
	<h4 class="acro display">Salto Avant</h4>	
	<h4 class="acro display">Salto Vrillé</h4>
		
</div>